CinemaApp/Models/TicketInfoViewModel.cs
namespace CinemaApp.Models
{
    public class TicketInfoViewModel
    {
        public List<TicketModel> Tickets { get; set; }
        public ScheduleModel Schedule { get; set; }
        public CustomerDataModel Customer { get; set; }
    }
}

CinemaApp/Controllers/TicketController.cs
using CinemaApp.Models;
using CinemaApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CinemaApp.Controllers
{
    public class TicketController : Controller
    {
        public readonly IReservationsRepository _reservationsRepository;
        public readonly IScheduleRepository _scheduleRepository;
        public readonly EmailSender _emailSender;

        public TicketController(IScheduleRepository scheduleRepository, EmailSender emailSender, IReservationsRepository reservationsRepository)
        {

            _scheduleRepository = scheduleRepository;
            _emailSender = emailSender;
            _reservationsRepository = reservationsRepository;
        }
        public IActionResult Index(int id)
        {
            var schedule = _scheduleRepository.GetScheduleById(id);
            var reservation = _reservationsRepository.GetReservationsForSchedule(id).ToList();

            var model = new TicketIndexViewModel
            {
                Schedule = schedule,
                Reservations = reservation
            };

            return View(model);
        }
        [HttpPost]
        public IActionResult TicketInfo([FromRoute] int id ,[FromBody] List<TicketModel> tickets)
        {
            
            var schedule = _scheduleRepository.GetScheduleById(id);

            var model = new TicketInfoViewModel
            {
                Tickets = tickets,
                Schedule = schedule
            };
           
            return View(model);
        }
        public IActionResult CustomerData([FromForm] TicketInfoViewModel model)
        {
                    
            return View(model);
        }
        [HttpPost]
        public IActionResult TicketPayment(TicketInfoViewModel model)
        {
           
            model.Schedule = _scheduleRepository.GetScheduleById(model.Schedule.ID);
            return View(model);
        }
        [HttpPost]
        public IActionResult Summary(TicketInfoViewModel model)
        {
            var schedule = _scheduleRepository.GetScheduleById(model.Schedule.ID);

            List<ReservationModel> reservations = new List<ReservationModel>();

            foreach (var res in model.Tickets)
            {
                var r = new ReservationModel
                {
                    SeanceID = schedule.ID,
                    Row = res.Row,
                    Place = res.Place,
                    ReservationDate = DateTime.Now,
                    FirstName = model.Customer.FirstName,
                    LastName = model.Customer.LastName,
                    Phone = model.Customer.Phone,
                    Email = model.Customer.Email


                };
                reservations.Add(r);
            }
            var summaryModel = new SummaryModel
            {
                Reservations = reservations,
                Schedule = schedule
                
            };


            if (!AddReservation(summaryModel))
            {
                return NotFound();
            }

            if (!PDFClass.DownloadPdf(summaryModel)) { return NotFound(); }

            var emailSubject = "Zakup biletów";
            var emailMessage = $"Zakup biletów na seans \"{summaryModel.Schedule.Movie}\" przez klienta {model.Customer.FirstName} {model.Customer.LastName}";

            if (!_emailSender.SendEmail(model.Customer.Email, emailSubject, emailMessage,summaryModel.PDFUrl))  {  return NotFound();  }

            return View("Summary", summaryModel);

        }
        public bool AddReservation(SummaryModel summaryModel)
        {
            try
            {
                foreach (var res in summaryModel.Reservations)
                {
                    _reservationsRepository.AddReservation(res);

                }
                return true;

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return false;
            
        }

        
    }
}

CinemaApp/Views/Ticket/CustomerData.cshtml
@model TicketInfoViewModel
@{
}



@using (Html.BeginForm("TicketPayment", "Ticket", FormMethod.Post))
{
    @Html.ValidationSummary();
    

    <div class="form-group">
        @Html.LabelFor(m => m.Customer.FirstName)
        @Html.TextBoxFor(m => m.Customer.FirstName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.FirstName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Customer.LastName)
        @Html.TextBoxFor(m => m.Customer.LastName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.LastName, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Customer.Email)
        @Html.TextBoxFor(m => m.Customer.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.Email, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Customer.Phone)
        @Html.TextBoxFor(m => m.Customer.Phone, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Customer.Phone, "", new { @class = "text-danger", @type="number"})
    </div>


    @foreach (var ticket in Model.Tickets)
    {
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Row" value="@ticket.Row" />
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Place" value="@ticket.Place" />
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Price" value="@ticket.Price" />

    }
    <input type="hidden" name="Schedule.ID" value="@Model.Schedule.ID" />


    <input class="bg-primary" type="submit" value="Przejdź dalej" />
}

CinemaApp/Views/Ticket/Index.cshtml
@model TicketIndexViewModel
@{
}
<script>
    let id=@Model.Schedule.ID;
</script>
<h1>@Model.Schedule.Movie.Title</h1>
<h2>@Model.Schedule.Hall.HallName</h2>
<h3>@Model.Schedule.Date</h3>

<br />
<hr />
<br />

<h5>Lista biletów </h5>
<ul id="TicketList"></ul>

<section>

    <center>
        <h3>Ekran</h3>
        <div style="width:80%;height:30px;background-color:grey;"></div>
    </center>

    <div class="seats_container">

        @for (int r = 0; r <= 10; r++)
        {
            <div class="seats_Row">
                   <span>Rząd:@r</span>

                @{
                    var display = "";
                    var avaible = "avaibleSit";
                 }

                   @for (int p = 0; p <= 10; p++)
                    {

                    display = "";
                    avaible = "avaibleSit";

                    if (Model.Reservations.Any(res => res.Row == r && res.Place == p)) { display = "disabled"; avaible = ""; }

                        <div id="r:@r,p:@p"  class= @avaible>
                             <button @display onclick='selectSit("@r","@p")'>@p</button>
                        </div>
                    }
            </div>
 
        }
    </div>
 
</section>

<button id="purscheButton" disabled onclick="pursche()">Zakup</button>

CinemaApp/Views/Ticket/Summary.cshtml
@model SummaryModel
@{
}
<h1 class="text-center">Podsumowanie</h1>

<h3 class="text-success text-center">Zakup wykonany pomyślnie</h3>


<div class="dowloadTicket">
    <iframe src="~/pdf/@Model.PDFUrl" style="width:100%; height:600px;"></iframe>

</div>

CinemaApp/Views/Ticket/TicketBuy.cshtml
@{
}

CinemaApp/Views/Ticket/TicketInfo.cshtml
@model TicketInfoViewModel

@{
    ViewData["Title"] = "Informacja o biletach";
}

<div class="container">
    <h1 class="text-center">Informacja o wybranych biletach</h1>

    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Rząd</th>
                        <th>Miejsce</th>
                        <th>Cena</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var ticket in Model.Tickets)
                    {
                        <tr>
                            <td>@ticket.Row</td>
                            <td>@ticket.Place</td>
                            <td>@ticket.Price</td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Film</th>
                        <th>Sala</th>
                        <th>Data</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>

                        <td>@Model.Schedule.Movie.Title</td>
                        <td>@Model.Schedule.Hall.HallName</td>
                        <td>@Model.Schedule.Date</td>

                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <form asp-action="CustomerData" method="post">
        <input type="submit" value="Przejdź dalej" class="btn btn-primary" />
        @foreach (var ticket in Model.Tickets)
        {
            <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Row" value="@ticket.Row" />
            <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Place" value="@ticket.Place" />
            <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Price" value="@ticket.Price" />

        }
        <input class ="bg-primary" type="hidden" name="Schedule.ID" value="@Model.Schedule.ID" />
       
    </form>
</div>

CinemaApp/Views/Ticket/TicketPay.cshtml
@model TicketInfoViewModel
@{
}
    <h1 class="text-center">Informacje o zakupie</h1>

    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Rząd</th>
                        <th>Miejsce</th>
                        <th>Cena</th>

                    </tr>
                </thead>
                <tbody>
                @foreach (var ticket in Model.Tickets)
                {
                            <tr>
                                <td>@ticket.Row</td>
                                <td>@ticket.Place</td>
                                <td>@ticket.Price</td>

                            </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Film</th>
                        <th>Sala</th>
                        <th>Data</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>

                        <td>@Model.Schedule.Movie.Title</td>
                        <td>@Model.Schedule.Hall.HallName</td>
                        <td>@Model.Schedule.Date</td>

                    </tr>
                </tbody>
            </table>
        </div>
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
                <tr>

                    <th>Imię</th>
                    <th>Nazwisko</th>
                    <th>Email</th>
                    <th>Telefon</th>


                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>@Model.Customer.FirstName</td>
                    <td>@Model.Customer.LastName</td>
                    <td>@Model.Customer.Email</td>
                    <td>@Model.Customer.Phone</td>
                </tr>
            </tbody>
        </table>
    </div>
    </div>

@using (Html.BeginForm("Pay", "Ticket", FormMethod.Post))
{
    <input type="hidden" name="Schedule.ID" value="@Model.Schedule.ID" />

    <input type="hidden" name="Customer.FirstName" value="@Model.Customer.FirstName" />
    <input type="hidden" name="Customer.lastName" value="@Model.Customer.LastName" />
    <input type="hidden" name="Customer.Email" value="@Model.Customer.Email" />
    <input type="hidden" name="Customer.Phone" value="@Model.Customer.Phone" />


    @foreach (var ticket in Model.Tickets)
    {
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Row" value="@ticket.Row" />
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Place" value="@ticket.Place" />
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Price" value="@ticket.Price" />

    }

    <!-- Add payment gateway here-->
    <input type="submit" value="Zapłać" />
}

CinemaApp/Views/Ticket/TicketPayment.cshtml
@model TicketInfoViewModel
@{
}
    <h1 class="text-center">Informacje o zakupie</h1>

    <div class="row">
        <div class="col-md-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Rząd</th>
                        <th>Miejsce</th>
                        <th>Cena</th>

                    </tr>
                </thead>
                <tbody>
                @foreach (var ticket in Model.Tickets)
                {
                            <tr>
                                <td>@ticket.Row</td>
                                <td>@ticket.Place</td>
                                <td>@ticket.Price</td>

                            </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Film</th>
                        <th>Sala</th>
                        <th>Data</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>

                        <td>@Model.Schedule.Movie.Title</td>
                        <td>@Model.Schedule.Hall.HallName</td>
                        <td>@Model.Schedule.Date</td>

                    </tr>
                </tbody>
            </table>
        </div>
    <div class="col-md-6">
        <table class="table table-striped">
            <thead>
                <tr>

                    <th>Imię</th>
                    <th>Nazwisko</th>
                    <th>Email</th>
                    <th>Telefon</th>


                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>@Model.Customer.FirstName</td>
                    <td>@Model.Customer.LastName</td>
                    <td>@Model.Customer.Email</td>
                    <td>@Model.Customer.Phone</td>
                </tr>
            </tbody>
        </table>
    </div>
    </div>

@using (Html.BeginForm("Summary", "Ticket", FormMethod.Post))
{
    <input type="hidden" name="Schedule.ID" value="@Model.Schedule.ID" />

    <input type="hidden" name="Customer.FirstName" value="@Model.Customer.FirstName" />
    <input type="hidden" name="Customer.lastName" value="@Model.Customer.LastName" />
    <input type="hidden" name="Customer.Email" value="@Model.Customer.Email" />
    <input type="hidden" name="Customer.Phone" value="@Model.Customer.Phone" />


    @foreach (var ticket in Model.Tickets)
    {
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Row" value="@ticket.Row" />
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Place" value="@ticket.Place" />
        <input type="hidden" name="Tickets[@Model.Tickets.IndexOf(ticket)].Price" value="@ticket.Price" />

    }

    <!-- Add payment gateway here-->
    <input class ="bg-primary" type="submit" value="Zapłać" />
}